---
title: "Project 1"
author: "Maya Szymborski"
format: 
  html:
    toc: true
    toc-depth: 3
    toc-location: right
editor: source
execute:
  error: true
  warning: false
  message: false
---

# Introduction

yada yada yada

# Part 1: Data Processing

yada yada yada

```{r}
# attach packages 
library(httr)
library(jsonlite)
library(tidyverse)
library(lubridate)
```

## Explore PUMS Census API

yada yada yada

```{r}
# establish API key

api_key <- "9565ad3d32410ea2b7caa601ff9c5c4467f789d7"

# try calling to API using example

url1 <- paste0(
  "https://api.census.gov/data/2024/acs/acs1/pums?",
  "get=SEX,PWGTP,MAR&",
  "for=state:*&",
  "SCHL=24&",
  "key=",
  api_key
)

response <- GET(url1)

response

# convert response to text/character string & 
# parse the JSON text into an R object
data <- fromJSON(rawToChar(response$content))

# look at returned data
head(data)

# make the first row the column names, 
# then remove the first row
column_names <- data[1, ]
data <- data[-1, ]

# convert to a tibble
data <- as_tibble(data)

# make sure tibble has the correct column names
names(data) <- column_names

# check
head(data)

# use process to create a helper function & then test it

query_api <- function(url) {
  
  response <- GET(url)
  
  data <- fromJSON(rawToChar(response$content))
  
  column_names <- data[1, ]
  data <- data[-1, ]
  
  data <- as_tibble(data)
  
  names(data) <- column_names
  
  return(data)
}

test <- query_api(url1)

test
```

yada yada yada

## Parsing Variable Values

yada yada yada

```{r}
# check 2024 PUMS variable data

url_2024 <- "https://api.census.gov/data/2024/acs/acs1/pums/variables.json"

info_2024 <- GET(url_2024)

data_2024 <- fromJSON(rawToChar(info_2024$content))

# inspect structure & variables 

str(data_2024, max.level = 2)
names(data_2024)
names(data_2024$variables) [1:10]

# create function & test it

PUMS_var <- c("AGEP", "GASP", "GRPIP", "JWAP", "JWDP", "JWMNP", "PWGTP",
  "FER", "HHL", "SCH", "SCHL", "SEX",
  "REGION", "DIVISION")

get_var <- function(year) {
  
  url1 <- paste0(
    "https://api.census.gov/data/",
    year,
    "/acs/acs1/pums/variables.json"
  )
  
  response <- GET(url1)
  
  data <- fromJSON(rawToChar(response$content))
  
  # keep requested variables
  var <- PUMS_var
  if (year == 2021 | year == 2022) {
    var <- c(var, "ST")
  } else {
    var <- c(var, "STATE")
  }
  
  variables <- data$variables[var]
  
  return(variables)
}

test_2024 <- get_var(2024)

names(test_2024)
```

works! so do on 2021-2023 data as well + yada yada

```{r}
data_2024 <- get_var(2024)
names(data_2024)

data_2023 <- get_var(2023)
names(data_2023)

data_2022 <- get_var(2022)
names(data_2022)

data_2021 <- get_var(2021)
names(data_2021)

# save as .rds in data folder

saveRDS(data_2024, "data/data_2024.rds")
saveRDS(data_2023, "data/data_2023.rds")
saveRDS(data_2022, "data/data_2022.rds")
saveRDS(data_2021, "data/data_2021.rds")
```

## Parsing API Data

### Helper Functions

```{r}
# make helper function to return available geography 

# inspect for specific_geography
data_2024$STATE$values
data_2024$REGION$values
data_2024$DIVISION$values

state_values <- data_2024$STATE$values$item
state_values
names(state_values)
unlist(state_values) # turn nested list into a simplified list

get_geo <- function(year, geography) {
  
  # load variable values for selected year
  var_data <- readRDS(
    paste0(
      "data/data_",
      year,
      ".rds"
    )
  )
  
  # use ST for 2021/2022 and STATE for 2023/2024
  if (geography == "State" && year %in% c(2021, 2022)) {
    geography <- "ST"
  } else {
    geography <- toupper(geography)
  }
  
  # get selected geography & match them
  geo_data <- var_data[[geography]] 
  
  # return geography codes and names
  geo_val <- unlist(geo_data$values$item)
  
  # remove Puerto Rico using `!grepl` which means "does not contain"
  geo_val <- geo_val[!grepl("Puerto Rico", geo_val)
                     ]
  
  return(geo_val)
}

# test helper function
get_geo(2024, "State")
get_geo(2023, "Region")
get_geo(2022, "Division")
```

```{r}
# make helper function that parses the time strings to return midpoint as time value

parse_time <- function(x, time_values) {
  
  # convert values to character to match metadata names
  x <- as.character(x)
  
  # return missing time values as NA
  x[x == "0"] <- NA
  
  # add leading 0's so codes match Census metadata
  x <- ifelse(
    is.na(x), 
    NA, 
    sprintf("%03d", as.numeric(x)
            )
    )
  
  # get time interval for each code
  intervals <- unname(time_values[x])
  
  # extract beginning and ending times
  start <- sub(" to .*", "", intervals)
  end <- sub(".* to ", "", intervals)
  
  # change Census AM/PM to standard AM/PM
  start <- gsub("a\\.m\\.", "AM", start)
  start <- gsub("p\\.m\\.", "PM", start)
  end <- gsub("a\\.m\\.", "AM", end)
  end <- gsub("p\\.m\\.", "PM", end)
  
  # convert times to POSIXct
  start_time <- strptime(start, format = "%I:%M %p")
  end_time <- strptime(end, format = "%I:%M %p")
  
  # calculate midpoint of each interval
  midpoint <- start_time + (end_time - start_time) / 2
  
  # return only time of day
  midpoint <- hms::as_hms(midpoint)
  
  return(midpoint)
}

```

```{r}
# JWAP metadata
url <- paste0(
  "https://api.census.gov/data/2024/acs/acs1/pums/variables/JWAP.json"
)

response <- GET(url)

fromJSON(rawToChar(response$content))

jwap_metadata <- fromJSON(rawToChar(response$content))

jwap_values <- unlist(jwap_metadata$values$item)

head(jwap_values)

arrive_test <- query_census(
  numeric_vars = c("JWAP", "PWGTP"),
  api_key = api_key
)
head(arrive_test$JWAP)

jwap_time <- parse_time(
  arrive_test$JWAP,
  jwap_values
)
head(jwap_time)
```

```{r}
# JWDP metadata 

url <- paste0(
  "https://api.census.gov/data/2024/acs/acs1/pums/variables/JWDP.json"
)

response_jwdp <- GET(url)

jwdp_metadata <- fromJSON(rawToChar(response_jwdp$content))

jwdp_values <- unlist(jwdp_metadata$values$item)

head(jwdp_values)

depart_test <- query_census(
  numeric_vars = c("JWDP", "PWGTP"),
  api_key = api_key
)

jwdp_time <- parse_time(
  depart_test$JWDP,
  jwdp_values
)

head(jwdp_time)
```

### Main Function
```{r}
# create main parsing function 

# first set up description and defaults 

query_census <- function(
    year = 2024,
    numeric_vars = c("AGEP", "PWGTP"),
    categorical_vars = "SEX",
    geography = "State",
    specific_geography = NULL,
    api_key
) 
  {
  # check for valid year
  if (!year %in% c(2021, 2022, 2023, 2024)) {
    stop("year must be in 2021, 2022, 2023, or 2024")
  }
  
  # specify numeric variables that can be returned
  allowed_num <- c("AGEP", "GASP", "GRPIP", "JWAP", "JWDP", "JWMNP", "PWGTP")
  
  # check
  if (!all(numeric_vars %in% allowed_num)) {
    stop("Invalid numeric variable. Choose from AGEP, GASP, GRPIP, JWAP, JWDP, JWMNP, and PWGTP.")
  }
  
  # make sure PWGTP is always returned 
  if (!"PWGTP" %in% numeric_vars) {
    stop("PWGTP must be included.")
  }
  
  # make sure another numeric variable is returned 
  if (length(numeric_vars) < 2) {
    stop("numeric_vars must included PWGTP and at least one other numeric variable.")
  }
  
  # specify categorical variables that can be returned 
  allowed_cat <- c("FER", "HHL", "SCH", "SCHL", "SEX")
  
  # check
  if (!all(categorical_vars %in% allowed_cat)) {
    stop("Invalid categorical variable. Choose from FER, HHL, SCH, SCHL, and SEX.")
  }
  
  # make sure at least one categorical variable is returned 
  if (length(categorical_vars) < 1) {
    stop("At least one categorical variable must be included.")
  }
  
  # specify geography levels that can be returned 
  allowed_geo <- c("Region", "Division", "State")
  
  # make sure only one level can be returned 
  if (length(geography) != 1 || !geography %in% allowed_geo) {
    stop("geography must be either Region, Division, or State.")
  }
  
  # specify the available geography that can be subset 
  geo_values <- get_geo(year, geography)
  
  # if no specific_geography, use North Carolina as default 
  if(is.null(specific_geography)) {
    specific_geography <- "North Carolina"
  }
  
  # return error if user requests Puerto Rico
  if (grepl("Puerto Rico", specific_geography, ignore.case = TRUE)) {
    stop("Puerto Rico is not included in this function.")
  }

  # find Census code for selected geography
  if (specific_geography == "all") {
    geo_code <- NULL
  } else {
    geo_code <- names(
    geo_values[grepl(
      specific_geography,
      geo_values,
      fixed = TRUE
    )]
  )
  }
  
  # make sure valid specific geography is returned 
  if (length(geo_code) == 0 && specific_geography != "all") {
    stop("Invalid specific_geography.")
  }
  
  # create API query
  get_variables <- paste(c(numeric_vars, categorical_vars),
                         collapse = ","
                         )
  
  if (specific_geography == "all") {
    for_part <- paste0(
      tolower(geography),
      ":*"
    )
  } else {
    for_part <- paste0(
      tolower(geography),
      ":",
      geo_code
    )
  }
  
  # create API URL
  url2 <- paste0(
    "https://api.census.gov/data/",
    year,
    "/acs/acs1/pums?",
    "get=",
    get_variables,
    "&for=",
    for_part,
    "&key=",
    api_key
  )
  
  # query API
  data <- query_api(url2)
  
  # convert numeric variables
  for (var in numeric_vars) {
    if (var %in% c("JWAP", "JWDP")) {
      
      # get metadata
      time_url <- paste0(
        "https://api.census.gov/data/",
      year,
      "/acs/acs1/pums/variables/",
      var,
      ".json"
      )
      
      time_response <- GET(time_url)
      
      time_metadata <- fromJSON(
        rawToChar(time_response$content)
        )
      
      time_values <- unlist(
        time_metadata$values$item
      )
      
      # convert Census time codes to midpoint times
      data[[var]] <- parse_time(
        data[[var]],
        time_values
      )
    } else {
      
      # convert regular numeric variables to numeric
      data[[var]] <- as.numeric(data[[var]])
    }
  }
  
  # load variable metadata
  var_data <- readRDS(paste0("data/data_", year, ".rds"))
  
  # convert categorical variables to factors
  for (var in categorical_vars) {
    levels <- unlist(var_data[[var]]$values$item)
    
    data[[var]] <- factor(
      data[[var]],
      levels = names(levels),
      labels = levels
    )
  }
  
  # give the data the census class
  class(data) <- c("census", class(data))
  
  return(data)
}
```

### Function Tests
```{r}
# test years

# valid
test_2021 <- query_census(
  year = 2021,
  api_key = api_key
  )
head(test_2021)

test_2023 <- query_census(
  year = 2023,
  api_key = api_key
  )
head(test_2023)

# invalid
query_census(
  year = 2002,
  api_key = api_key
  )

# test numeric variables

# valid
test_numeric <- query_census(
  numeric_vars = c("AGEP", "PWGTP"),
  api_key = api_key
  )
head(test_numeric)

# invalid numeric variables
query_census(
  numeric_vars = c("BDSP", "PWGTP"),
  api_key = api_key
  )

query_census(
  numeric_vars = c("AGEP", "GASP"),
  api_key = api_key
  )

query_census(
  numeric_vars = "PWGTP",
  api_key = api_key
  )

# test categorical variables

# valid
test_categorical <- query_census(
  numeric_vars = c("GASP", "PWGTP"),
  categorical_vars = c("FER", "SEX"),
  api_key = api_key
  )

head(test_categorical)
class(test_categorical$SEX)
levels(test_categorical$SEX)

# invalid
query_census(
  categorical_vars = "WAOB",
  api_key = api_key
  )

# test geography

# valid 
test_geo <- query_census(
  geography = "Region",
  specific_geography = "South",
  api_key = api_key
  )
head(test_geo)

test_geo2 <- query_census(
  specific_geography = "California",
  api_key = api_key
  )
head(test_geo2)

# invalid geography
query_census(
  geography = "All",
  api_key = api_key
  )

query_census(
  geography = c("Region", "Division"),
  api_key = api_key
  )

query_census(
  specific_geography = "Puerto Rico",
  api_key = api_key
  )

query_census(
  specific_geography = "Cuba",
  api_key = api_key
  )

# test default query
test_default <- query_census(
  api_key = api_key
  )
head(test_default)

# test time variable
test_time <- query_census(
  numeric_vars = c("JWAP", "PWGTP"),
  api_key = api_key
)
head(test_time$JWAP)
class(test_time$JWAP)

# test census class
class(test_time)

# general test
gen_test <- query_census(
  numeric_vars = c("JWAP", "PWGTP"),
  api_key = api_key
)
class(gen_test$JWAP)
class(gen_test$SEX)
levels(gen_test$SEX)
head(gen_test$SEX)
```

yada yada yada

## Combining Years

```{r}
# create function to specify multiple years of survey data

query_census_years <- function(
    years = c(2021, 2022, 2023, 2024),
    numeric_vars = c("AGEP", "PWGTP"),
    categorical_vars = "SEX",
    geography = "State",
    specific_geography = NULL,
    api_key
) {
  
  # check for valid years
  if (!all(years %in% c(2021, 2022, 2023, 2024))) {
    stop("years must be in 2021, 2022, 2023, or 2024")
  }
  
  # make sure at least one year in specified 
  if (length(years) < 1) {
    stop("At least one year must be specified.")
  }

  # create a list to store each year's data
  data_list <- list()

  # query each year
  for (i in seq_along(years)) {
    data_list[[i]] <- query_census(
      year = years[i],
      numeric_vars = numeric_vars,
      categorical_vars = categorical_vars,
      geography = geography,
      specific_geography = specific_geography,
      api_key = api_key
    )
    
    # add year variable
    data_list[[i]]$year <- years[i]
  }
  
  # combine all years into one tibble
  data <- bind_rows(data_list)
  
  return(data)
}
```

```{r}
# test function

combined_test <- query_census_years(
  years = c(2022, 2024),
  api_key = api_key
)
head(combined_test)
table(combined_test$year)
class(combined_test)

combined_all_years <- query_census_years(
  years = c(2021, 2022, 2023, 2024),
  api_key = api_key
)
head(combined_all_years)
table(combined_all_years$year)

combined_test2 <- query_census_years(
  years = c(2022, 2023, 2024),
  numeric_vars = c("GASP", "PWGTP"),
  categorical_vars = c("FER", "SEX"),
  geography = "State",
  specific_geography = "California",
  api_key = api_key
)
head(combined_test2)

combined_all_states <- query_census_years(
  years = c(2023, 2024),
  specific_geography = "all",
  api_key = api_key
)
table(combined_all_states$year)
```

# Part 2: Writing a Generic Function for Summarizing