---
title: "Project 1"
author: "Maya Szymborski"
format: html
editor: source
---

# Introduction

yada yada yada

# Part 1: Data Processing

yada yada yada

```{r}
# attach packages 
library(httr)
library(jsonlite)
library(tidyverse)
```

## Explore PUMS Census Api

yada yada yada

```{r}
# establish API key

api_key <- "9565ad3d32410ea2b7caa601ff9c5c4467f789d7"

# try calling to API using example

url <- paste0(
  "https://api.census.gov/data/2024/acs/acs1/pums?",
  "get=SEX,PWGTP,MAR&",
  "for=state:*&",
  "SCHL=24&",
  "key=",
  api_key
)

response <- GET(url)

response

# convert response to text/character string & 
# parse the JSON text into an R object
data <- fromJSON(rawToChar(response$content))

# look at returned data
head(data)

# make the first row the column names, 
# then remove the first row
column_names <- data[1, ]
data <- data[-1, ]

# convert to a tibble
data <- as_tibble(data)

# make sure tibble has the correct column names
names(data) <- column_names

# check
head(data)

# use process to create a function & then test it

query_api <- function(url) {
  
  response <- GET(url)
  
  data <- fromJSON(rawToChar(response$content))
  
  column_names <- data[1, ]
  
  data <- data[-1, ]
  
  data <- as_tibble(data)
  
  names(data) <- column_names
  
  return(data)
}

test <- query_api(url)

test
```

yada yada yada

## Parsing Variable Values

yada yada yada

```{r}
# check 2024 PUMS variable data

url_2024 <- "https://api.census.gov/data/2024/acs/acs1/pums/variables.json"

info_2024 <- GET(url_2024)

data_2024 <- fromJSON(rawToChar(info_2024$content))

# inspect structure & variables 

str(data_2024, max.level = 2)
names(data_2024)
names(data_2024$variables) [1:10]

# create function & test it

PUMS_var <- c("AGEP", "GASP", "GRPIP", "JWAP", "JWDP", "JWMNP", "PWGTP",
  "FER", "HHL", "SCH", "SCHL", "SEX",
  "REGION", "DIVISION")

get_var <- function(year) {
  
  url <- paste0(
    "https://api.census.gov/data/",
    year,
    "/acs/acs1/pums/variables.json"
  )
  
  response <- GET(url)
  
  data <- fromJSON(rawToChar(response$content))
  
  # keep requested variables
  var <- PUMS_var
  if (year == 2021 | year == 2022) {
    var <- c(var, "ST")
  } else {
    var <- c(var, "STATE")
  }
  
  variables <- data$variables[var]
  
  return(variables)
}

test_2024 <- get_var(2024)

test_2024
names(test_2024)
```

works! so do on 2021-2023 data as well + yada yada

```{r}
data_2024 <- get_var(2024)
names(data_2024)

data_2023 <- get_var(2023)
names(data_2023)

data_2022 <- get_var(2022)
names(data_2022)

data_2021 <- get_var(2021)
names(data_2021)

# save as .rds in data folder

saveRDS(data_2024, "data/data_2024.rds")
saveRDS(data_2023, "data/data_2023.rds")
saveRDS(data_2022, "data/data_2022.rds")
saveRDS(data_2021, "data/data_2021.rds")
```

## Parsing API Data

yada yada 
```{r}
# create main parsing function 

# first set up description and defaults 

query_census <- function(
    year = 2024,
    numeric_vars = c("AGEP", "PWGTP"),
    categorical_vars = "SEX",
    geography = "State",
    specific_geography = NULL
) 
  {
  # check for valid year
  if (!year %in% c(2021, 2022, 2023, 2024)) {
    stop("year must be in 2021, 2022, 2023, or 2024")
  }
  
  # specify numeric variables that can be returned
  allowed_num <- c("AGEP", "GASP", "GRPIP", "JWAP", "JWDP", "JWMNP", "PWGTP")
  
  # check
  if (!all(numeric_vars %in% allowed_num)) {
    stop("Invalid numeric variable. Choose from AGEP, GASP, GRPIP, JWAP, JWDP, JWMNP, and PWGTP.")
  }
  
  # make sure PWGTP is always returned 
  if (!"PWGTP" %in% numeric_vars) {
    stop("PWGTP must be included.")
  }
  
  # make sure another numeric variable is returned 
  if (length(numeric_vars) < 2) {
    stop("numeric_vars must included PWGTP and at least one other numeric variable.")
  }
  
  # specify categorical variables that can be returned 
  allowed_cat <- c("FER", "HHL", "SCH", "SCHL", "SEX")
  
  # check
  if (!all(categorical_vars %in% allowed_cat)) {
    stop("Invalid categorical variable. Choose from FER, HHL, SCH. SCHL, and SEX.")
  }
  
  # make sure at least one categorical variable is returned 
  if (length(categorical_vars) < 1) {
    stop("At least one categorical variable must be included.")
  }
  
  # specify geography levels that can be returned 
  allowed_geo <- c("Region", "Division", "State")
  
  # make sure only one level can be returned 
  if (length(geography) != 1 || !geography %in% allowed_geo) {
    stop("geography must be either Region, Division, or State.")
  }
  
  # specify the specific geography that can be subset 
  
}

# check this function

query_census(year = 2002)

query_census(numeric_vars = c("AGEP", "PWGTP")
             )

query_census(numeric_vars = c("BDSP", "PWGTP")
             )

query_census(numeric_vars = c("AGEP", "GASP")
             )

query_census(numeric_vars = "PWGTP")

query_census(categorical_vars = "WAOB")

query_census(
  numeric_vars = c("GASP", "PWGTP"),
  categorical_vars = c("FER", "SEX")
)

query_census(geography = "Region")

query_census(geography = "All")

query_census(geography = c("Region", "Division")
             )
```


